"""initial seasons schema

Revision ID: 001
Revises: 
Create Date: 2025-08-25 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('episodeOrder', sa.Integer(), nullable=True),
    sa.Column('premiereDate', sa.String(length=255), nullable=True),
    sa.Column('endDate', sa.String(length=255), nullable=True),
    sa.Column('network', mysql.JSON(), nullable=True),
    sa.Column('webChannel', mysql.JSON(), nullable=True),
    sa.Column('image', mysql.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('_links', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    # ### end Alembic commands ###